format = """
$directory\
[ÓÇ∞ ](fg:#88C0D0 bg:#1d2230)\
$git_branch\
$git_status\
[ÓÇ∞ ](fg:#1d2230)\
\n$character

"""

right_format = """
$cmd_duration\
$username\
ü¶¶
$time
"""

add_newline = true

[username]
style_user = "white bold"
style_root = "black bold"
format = "user: [$user]($style) "
disabled = false

[fill]
symbol = ' '

[directory]
style = "fg:#2E3440 bg:#88C0D0 bold"
truncation_length = 8
truncate_to_repo = true
truncation_symbol = 'ÔÅº ‚Ä¶/ '
read_only = ' Û∞åæ ' # nf-md-lock
read_only_style = 'fg:#f7768e bg:#1a1b26'
format = '[ $path ]($style)[$read_only]($read_only_style)'

[git_branch]
symbol = "Ôêò"
style = "bg:#1d2230"
format = '[[ $symbol $branch ](fg:#769ff0 bg:#1d2230)]($style)'

[git_status]
style = "bg:#1d2230"
format = '[[($all_status$ahead_behind )](fg:#769ff0 bg:#1d2230)]($style)'

[cmd_duration]
min_time = 0
style = 'fg:#e0af68'
format = "[$duration]($style)" # nf-pl-right_soft_divider, nf-mdi-clock

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
# style = "bg:#1d2230"
format = '[[ ÓÇ≥ ÔÄó $time ](fg:#a0a9cb)]($style)'

